server:
  port: 8089

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false

  application:
    is-debug: true
  datasource:
    writer:
      hikari:
        #        url: jdbc:h2:mem:product
        #        driverClassName: org.h2.Driver
        #        username: product
        #        password: product
        jdbc-url: jdbc:h2:mem:product;mode=mysql;database_to_lower=true;
        driver-class-name: org.h2.Driver
        username: product
        password: product
        pool-name: api-pool-writer
        minimum-idle: 5
        maximum-pool-size: 10
        connection-timeout: 5000
        data-source-properties:
          idleTimeout: ${DB_IDLE_TIMEOUT:600000}
          maxLifetime: ${DB_MAX_LIFETIME:1800000}
          minimumIdle: ${DB_MINIMUM_IDLE:5}
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
        connection-test-query: select 1
        auto-commit: false
    reader:
      hikari:
        #        url: jdbc:h2:mem:product
        #        driverClassName: org.h2.Driver
        #        username: product
        #        password: product
        jdbc-url: jdbc:h2:mem:product;mode=mysql;database_to_lower=true;
        driver-class-name: org.h2.Driver
        username: product
        password: product
        pool-name: api-pool-reader
        minimum-idle: 5
        maximum-pool-size: 10
        connection-timeout: 5000
        data-source-properties:
          idleTimeout: ${DB_IDLE_TIMEOUT:600000}
          maxLifetime: ${DB_MAX_LIFETIME:1800000}
          minimumIdle: ${DB_MINIMUM_IDLE:5}
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
        connection-test-query: select 1
        auto-commit: false
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

    open-in-view: false
    generate-ddl: false
    show-sql: true

    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.globally_quoted_identifiers_skip_column_definitions: true

#logging:
#  config: classpath:log4j2/idus-log4j2-local.xml

management:
  health:
    redis:
      enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: true

#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  show-actuator: false
#  writer-with-default-pretty-printer: false
#  api-docs:
#    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
#    resolve-schema-properties: true
#    path: /docs/openapi
#  swagger-ui:
#    enabled: ${SPRINGDOC_SWAGGER_ENABLED:true}
#    path: /docs/swagger

feign:
  client:
    config:
      default:
        connectTimeout: ${SPRING_FEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT:10000}
        readTimeout: ${SPRING_FEIGN_CLIENT_DEFAULT_READ_TIMEOUT:10000}
        loggerLevel: ${SPRING_FEIGN_CLIENT_DEFAULT_LOGGER_LEVEL:HEADERS}
  httpclient:
    enabled: true
  compression:
    request:
      enabled: false
    response:
      enabled: false