spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api}
    description: ${SPRING_APPLICATION_DESCRIPTION:api-server}
    is-debug: false
    encoding: UTF-8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time: iso
      date: iso
  lifecycle:
    timeout-per-shutdown-phase: 1m
  sleuth:
    sampler:
      probability: ${SPRING_SLEUTH_SAMPLER_PROBABILITY:1.0}
    async:
      enabled: true
    feign:
      enabled: true
  sql:
    init:
      mode: never
  devtools:
    restart:
      enabled: false
  exception-handler:
    debug:
      echo: false
      enabled: false
    response-body: global
    response-type: normal

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false
  writer-with-default-pretty-printer: false
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    resolve-schema-properties: true
    path: /docs/openapi
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_ENABLED:true}
    path: /docs/swagger
    tags-sorter: alpha

pagination:
  cursor:
    next: "1"
    limit: 20